<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


/**
 * Operator used for the filtering of balances can be greater than/equal, less than/equal, greater than, less than, equal or not.
 * 
 * 
 */
enum BalanceOperator: string
{
    case Gte = 'gte';
    case Lte = 'lte';
    case Gt = 'gt';
    case Lt = 'lt';
    case E = 'e';
    case Ne = 'ne';
}
