<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class CreateSecretRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\formance\formance\Models\Shared\CreateSecretRequest $createSecretRequest = null;
    
    /**
     * Client ID
     * 
     * @var string $clientId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=clientId')]
    public string $clientId;
    
	public function __construct()
	{
		$this->createSecretRequest = null;
		$this->clientId = "";
	}
}
