<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


class CreateScopeResponse
{
	
    public string $contentType;
    
    /**
     * Created scope
     * 
     * @var ?\formance\formance\Models\Shared\CreateScopeResponse $createScopeResponse
     */
	
    public ?\formance\formance\Models\Shared\CreateScopeResponse $createScopeResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->createScopeResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
