<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


class CreateTransactionResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\formance\formance\Models\Shared\CreateTransactionResponse $createTransactionResponse
     */
	
    public ?\formance\formance\Models\Shared\CreateTransactionResponse $createTransactionResponse = null;
    
    /**
     * Error
     * 
     * @var ?\formance\formance\Models\Shared\ErrorResponse $errorResponse
     */
	
    public ?\formance\formance\Models\Shared\ErrorResponse $errorResponse = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->createTransactionResponse = null;
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
