<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class DebitWalletRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\formance\formance\Models\Shared\DebitWalletRequest $debitWalletRequest = null;
    
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->debitWalletRequest = null;
		$this->id = "";
	}
}
