<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class DeleteSecretRequest
{
    /**
     * Client ID
     * 
     * @var string $clientId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=clientId')]
    public string $clientId;
    
    /**
     * Secret ID
     * 
     * @var string $secretId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=secretId')]
    public string $secretId;
    
	public function __construct()
	{
		$this->clientId = "";
		$this->secretId = "";
	}
}
