<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class DeleteScopeFromClientRequest
{
    /**
     * Client ID
     * 
     * @var string $clientId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=clientId')]
    public string $clientId;
    
    /**
     * Scope ID
     * 
     * @var string $scopeId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=scopeId')]
    public string $scopeId;
    
	public function __construct()
	{
		$this->clientId = "";
		$this->scopeId = "";
	}
}
