<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


class GetBalancesAggregatedResponse
{
    /**
     * OK
     * 
     * @var ?\formance\formance\Models\Shared\AggregateBalancesResponse $aggregateBalancesResponse
     */
	
    public ?\formance\formance\Models\Shared\AggregateBalancesResponse $aggregateBalancesResponse = null;
    
	
    public string $contentType;
    
    /**
     * Error
     * 
     * @var ?\formance\formance\Models\Shared\ErrorResponse $errorResponse
     */
	
    public ?\formance\formance\Models\Shared\ErrorResponse $errorResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->aggregateBalancesResponse = null;
		$this->contentType = "";
		$this->errorResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
