<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


class GetInstanceStageHistoryResponse
{
	
    public string $contentType;
    
    /**
     * General error
     * 
     * @var ?\formance\formance\Models\Shared\Error $error
     */
	
    public ?\formance\formance\Models\Shared\Error $error = null;
    
    /**
     * The workflow instance stage history
     * 
     * @var ?\formance\formance\Models\Shared\GetWorkflowInstanceHistoryStageResponse $getWorkflowInstanceHistoryStageResponse
     */
	
    public ?\formance\formance\Models\Shared\GetWorkflowInstanceHistoryStageResponse $getWorkflowInstanceHistoryStageResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->error = null;
		$this->getWorkflowInstanceHistoryStageResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
