<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class GetWorkflowRequest
{
    /**
     * The flow id
     * 
     * @var string $flowId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=flowId')]
    public string $flowId;
    
	public function __construct()
	{
		$this->flowId = "";
	}
}
