<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


class ListClientsResponse
{
	
    public string $contentType;
    
    /**
     * List of clients
     * 
     * @var ?\formance\formance\Models\Shared\ListClientsResponse $listClientsResponse
     */
	
    public ?\formance\formance\Models\Shared\ListClientsResponse $listClientsResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->listClientsResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
