<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


class ListUsersResponse
{
	
    public string $contentType;
    
    /**
     * List of users
     * 
     * @var ?\formance\formance\Models\Shared\ListUsersResponse $listUsersResponse
     */
	
    public ?\formance\formance\Models\Shared\ListUsersResponse $listUsersResponse = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->listUsersResponse = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
