<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;


/**
 * Metadata - Filter accounts by metadata key value pairs. The filter can be used like this metadata[key]=value1&metadata[a.nested.key]=value2
 * 
 * @package formance\formance\Models\Operations
 * @access public
 */
class Metadata
{
	public function __construct()
	{
	}
}
