<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class ReadUserRequest
{
    /**
     * User ID
     * 
     * @var string $userId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=userId')]
    public string $userId;
    
	public function __construct()
	{
		$this->userId = "";
	}
}
