<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class UpdateScopeRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\formance\formance\Models\Shared\UpdateScopeRequest $updateScopeRequest = null;
    
    /**
     * Scope ID
     * 
     * @var string $scopeId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=scopeId')]
    public string $scopeId;
    
	public function __construct()
	{
		$this->updateScopeRequest = null;
		$this->scopeId = "";
	}
}
