<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Operations;

use \formance\formance\Utils\SpeakeasyMetadata;
class VoidHoldRequest
{
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=hold_id')]
    public string $holdId;
    
	public function __construct()
	{
		$this->holdId = "";
	}
}
