<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class Config
{
	#[\JMS\Serializer\Annotation\SerializedName('storage')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\LedgerStorage')]
    public LedgerStorage $storage;
    
	public function __construct()
	{
		$this->storage = new \formance\formance\Models\Shared\LedgerStorage();
	}
}
