<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class ConfigsResponseCursor
{
    /**
     * $data
     * 
     * @var array<\formance\formance\Models\Shared\WebhooksConfig> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<formance\formance\Models\Shared\WebhooksConfig>')]
    public array $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('hasMore')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $hasMore;
    
	public function __construct()
	{
		$this->data = [];
		$this->hasMore = false;
	}
}
