<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class ConnectorsConfigsResponseConnector
{
	#[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\Key')]
    public Key $key;
    
	public function __construct()
	{
		$this->key = new \formance\formance\Models\Shared\Key();
	}
}
