<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class ConnectorsConfigsResponseData
{
	#[\JMS\Serializer\Annotation\SerializedName('connector')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\ConnectorsConfigsResponseDataConnector')]
    public ConnectorsConfigsResponseDataConnector $connector;
    
	public function __construct()
	{
		$this->connector = new \formance\formance\Models\Shared\ConnectorsConfigsResponseDataConnector();
	}
}
