<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class ConnectorsResponseData
{
	#[\JMS\Serializer\Annotation\SerializedName('enabled')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $enabled = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('provider')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\Connector>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Connector $provider = null;
    
	public function __construct()
	{
		$this->enabled = null;
		$this->provider = null;
	}
}
