<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class CreateScopeResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\Scope')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Scope $data = null;
    
	public function __construct()
	{
		$this->data = null;
	}
}
