<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * DebitWalletResponse - Wallet successfully debited as a pending hold
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class DebitWalletResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\Hold')]
    public Hold $data;
    
	public function __construct()
	{
		$this->data = new \formance\formance\Models\Shared\Hold();
	}
}
