<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class Error
{
	#[\JMS\Serializer\Annotation\SerializedName('errorCode')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\ErrorCode>')]
    public ErrorCode $errorCode;
    
	#[\JMS\Serializer\Annotation\SerializedName('errorMessage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $errorMessage;
    
	public function __construct()
	{
		$this->errorCode = \formance\formance\Models\Shared\ErrorCode::Validation;
		$this->errorMessage = "";
	}
}
