<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


enum ErrorCode: string
{
    case Validation = 'VALIDATION';
    case NotFound = 'NOT_FOUND';
}
