<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * GetHoldsResponse - Holds
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class GetHoldsResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('cursor')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\GetHoldsResponseCursor')]
    public GetHoldsResponseCursor $cursor;
    
	public function __construct()
	{
		$this->cursor = new \formance\formance\Models\Shared\GetHoldsResponseCursor();
	}
}
