<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * GetTransactionResponse - OK
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class GetTransactionResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\ExpandedTransaction')]
    public ExpandedTransaction $data;
    
	public function __construct()
	{
		$this->data = new \formance\formance\Models\Shared\ExpandedTransaction();
	}
}
