<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * GetVersionsResponse - OK
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class GetVersionsResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('env')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $env;
    
	#[\JMS\Serializer\Annotation\SerializedName('region')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $region;
    
    /**
     * $versions
     * 
     * @var array<\formance\formance\Models\Shared\Version> $versions
     */
	#[\JMS\Serializer\Annotation\SerializedName('versions')]
    #[\JMS\Serializer\Annotation\Type('array<formance\formance\Models\Shared\Version>')]
    public array $versions;
    
	public function __construct()
	{
		$this->env = "";
		$this->region = "";
		$this->versions = [];
	}
}
