<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class LedgerInfo
{
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('storage')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\LedgerInfoStorage')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?LedgerInfoStorage $storage = null;
    
	public function __construct()
	{
		$this->name = null;
		$this->storage = null;
	}
}
