<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * ListScopesResponse - List of scopes
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class ListScopesResponse
{
    /**
     * $data
     * 
     * @var ?array<\formance\formance\Models\Shared\Scope> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<formance\formance\Models\Shared\Scope>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $data = null;
    
	public function __construct()
	{
		$this->data = null;
	}
}
