<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class Log
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\LogData')]
    public LogData $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('date')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $date;
    
	#[\JMS\Serializer\Annotation\SerializedName('hash')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $hash;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\LogType>')]
    public LogType $type;
    
	public function __construct()
	{
		$this->data = new \formance\formance\Models\Shared\LogData();
		$this->date = new \DateTime();
		$this->hash = "";
		$this->id = 0;
		$this->type = \formance\formance\Models\Shared\LogType::NewTransaction;
	}
}
