<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class Payment
{
	#[\JMS\Serializer\Annotation\SerializedName('accountID')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $accountID;
    
    /**
     * $adjustments
     * 
     * @var array<\formance\formance\Models\Shared\PaymentAdjustment> $adjustments
     */
	#[\JMS\Serializer\Annotation\SerializedName('adjustments')]
    #[\JMS\Serializer\Annotation\Type('array<formance\formance\Models\Shared\PaymentAdjustment>')]
    public array $adjustments;
    
	#[\JMS\Serializer\Annotation\SerializedName('asset')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $asset;
    
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('initialAmount')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $initialAmount;
    
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\PaymentMetadata')]
    public PaymentMetadata $metadata;
    
	#[\JMS\Serializer\Annotation\SerializedName('provider')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\Connector>')]
    public Connector $provider;
    
	#[\JMS\Serializer\Annotation\SerializedName('raw')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\PaymentRaw')]
    public PaymentRaw $raw;
    
	#[\JMS\Serializer\Annotation\SerializedName('reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $reference;
    
	#[\JMS\Serializer\Annotation\SerializedName('scheme')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\PaymentScheme>')]
    public PaymentScheme $scheme;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\PaymentStatus>')]
    public PaymentStatus $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\PaymentType>')]
    public PaymentType $type;
    
	public function __construct()
	{
		$this->accountID = "";
		$this->adjustments = [];
		$this->asset = "";
		$this->createdAt = new \DateTime();
		$this->id = "";
		$this->initialAmount = 0;
		$this->metadata = new \formance\formance\Models\Shared\PaymentMetadata();
		$this->provider = \formance\formance\Models\Shared\Connector::Stripe;
		$this->raw = new \formance\formance\Models\Shared\PaymentRaw();
		$this->reference = "";
		$this->scheme = \formance\formance\Models\Shared\PaymentScheme::Visa;
		$this->status = \formance\formance\Models\Shared\PaymentStatus::Pending;
		$this->type = \formance\formance\Models\Shared\PaymentType::PayIn;
	}
}
