<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class PostTransaction
{
    /**
     * $metadata
     * 
     * @var array<string, string> $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('array<string, string>')]
    public array $metadata;
    
    /**
     * $postings
     * 
     * @var ?array<\formance\formance\Models\Shared\Posting> $postings
     */
	#[\JMS\Serializer\Annotation\SerializedName('postings')]
    #[\JMS\Serializer\Annotation\Type('array<formance\formance\Models\Shared\Posting>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $postings = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('reference')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $reference = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('script')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\PostTransactionScript')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PostTransactionScript $script = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('timestamp')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $timestamp = null;
    
	public function __construct()
	{
		$this->metadata = [];
		$this->postings = null;
		$this->reference = null;
		$this->script = null;
		$this->timestamp = null;
	}
}
