<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class Script
{
	#[\JMS\Serializer\Annotation\SerializedName('plain')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $plain;
    
	#[\JMS\Serializer\Annotation\SerializedName('vars')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\Vars')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Vars $vars = null;
    
	public function __construct()
	{
		$this->plain = "";
		$this->vars = null;
	}
}
