<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class StageSendDestination
{
	#[\JMS\Serializer\Annotation\SerializedName('account')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendDestinationAccount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendDestinationAccount $account = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('payment')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendDestinationPayment')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendDestinationPayment $payment = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('wallet')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendDestinationWallet')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendDestinationWallet $wallet = null;
    
	public function __construct()
	{
		$this->account = null;
		$this->payment = null;
		$this->wallet = null;
	}
}
