<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class StageSendSource
{
	#[\JMS\Serializer\Annotation\SerializedName('account')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendSourceAccount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendSourceAccount $account = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('payment')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendSourcePayment')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendSourcePayment $payment = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('wallet')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendSourceWallet')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendSourceWallet $wallet = null;
    
	public function __construct()
	{
		$this->account = null;
		$this->payment = null;
		$this->wallet = null;
	}
}
