<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class StageSend
{
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\Monetary')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Monetary $amount = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('destination')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendDestination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendDestination $destination = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('source')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\StageSendSource')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StageSendSource $source = null;
    
	public function __construct()
	{
		$this->amount = null;
		$this->destination = null;
		$this->source = null;
	}
}
