<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class Storage
{
    /**
     * $migrations
     * 
     * @var ?array<\formance\formance\Models\Shared\MigrationInfo> $migrations
     */
	#[\JMS\Serializer\Annotation\SerializedName('migrations')]
    #[\JMS\Serializer\Annotation\Type('array<formance\formance\Models\Shared\MigrationInfo>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $migrations = null;
    
	public function __construct()
	{
		$this->migrations = null;
	}
}
