<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * StripeTransferResponse - OK
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class StripeTransferResponse
{
	public function __construct()
	{
	}
}
