<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * StripeTransferRequestMetadata - A set of key/value pairs that you can attach to a transfer object.
 * 
 * It can be useful for storing additional information about the transfer in a structured format.
 * 
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class StripeTransferRequestMetadata
{
	public function __construct()
	{
	}
}
