<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * TaskResponse - OK
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class TaskResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $data;
    
	public function __construct()
	{
		$this->data = null;
	}
}
