<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


class WalletWithBalancesBalances
{
	#[\JMS\Serializer\Annotation\SerializedName('main')]
    #[\JMS\Serializer\Annotation\Type('formance\formance\Models\Shared\AssetHolder')]
    public AssetHolder $main;
    
	public function __construct()
	{
		$this->main = new \formance\formance\Models\Shared\AssetHolder();
	}
}
