<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace formance\formance\Models\Shared;


/**
 * WalletsErrorResponse - Error
 * 
 * @package formance\formance\Models\Shared
 * @access public
 */
class WalletsErrorResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('errorCode')]
    #[\JMS\Serializer\Annotation\Type('enum<formance\formance\Models\Shared\WalletsErrorResponseErrorCode>')]
    public WalletsErrorResponseErrorCode $errorCode;
    
	#[\JMS\Serializer\Annotation\SerializedName('errorMessage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $errorMessage;
    
	public function __construct()
	{
		$this->errorCode = \formance\formance\Models\Shared\WalletsErrorResponseErrorCode::Validation;
		$this->errorMessage = "";
	}
}
